name: Build Artifact for Veracode Code Analysis

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      ref:
        required: true
        type: string
      token:
        required: true
        type: string
      event_name:
        required: true
        type: string

jobs:
  build-java-maven:
    if: ${{ inputs.event_name == 'java-maven' }}
    uses: ./.github/workflows/veracode-build-java-maven.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}

  build-java-gradle:
    if: ${{ inputs.event_name == 'java-gradle' }}
    uses: ./.github/workflows/veracode-build-java-gradle.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}

  build-source-code-scan:
    if: ${{ inputs.event_name == 'source-code' }}
    uses: ./.github/workflows/veracode-build-source-code.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}

  build-dot-net-package:
    if: ${{ inputs.event_name == 'dot-net' }}
    uses: ./.github/workflows/veracode-build-dot-net.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}

  build-go-package:
    if: ${{ inputs.event_name == 'go' }}
    uses: ./.github/workflows/veracode-build-go.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}

  build-dart-package:
    if: ${{ inputs.event_name == 'dart' }}
    uses: ./.github/workflows/veracode-build-dart.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}
      
  build-php-package:
    if: ${{ inputs.event_name == 'php' }}
    uses: ./.github/workflows/veracode-build-php.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}

  build-plsql-package:
    if: ${{ inputs.event_name == 'plsql' }}
    uses: ./.github/workflows/veracode-build-plsql.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}

  build-tsql-package:
    if: ${{ inputs.event_name == 'tsql' }}
    uses: ./.github/workflows/veracode-build-tsql.yml
    with:
      repository: ${{ inputs.repository }}
      ref: ${{ inputs.ref }}
      token: ${{ inputs.token }}
